---
title: "mapping_dashboard"
author: "Johannes Burgers"
date: "5/24/2021"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE, error=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE, error=FALSE)
```


```{r load_libraries}

library(tidyverse)
library(tidytext)
library(stringi)
library(scales)
library(stringr)
library(plotly)
library(textstem)
library(shiny)
library(lubridate)
```

```{r load_data}

dy_events <- read_csv("data/mapping_data_5_24.csv") 

dy_events <- dy_events %>% 
            rename_with(~ tolower(gsub(" ", "_", .x, fixed = TRUE))) %>% 
            mutate(true_x = true_x - 632)

```

```{r load_regions}

dy_regions <- read_csv("data/region_codes.csv")
dy_regions <- dy_regions %>% 
              rename(locationid = LocationID) %>% 
              rename(region = L_Region)

```

```{r join_regions}

dy_events <- dy_events %>% 
            left_join(dy_regions)

```


```{r clean_events}

dy_events <- dy_events %>% 
            mutate(startdate = as_date(startdate)) %>% 
            mutate(enddate = as_date (enddate)) %>%
            mutate(race_group = ifelse(race %in% c("White" ,"Black", "Indian"),race, "Mixed Ancestry"))

```

```{r export_updated}
write_csv(dy_events, "data/complete_mapping_data_05_24.csv")
```


```{r load_plotly_styles, echo=FALSE}

#Page styling

#This is where you create your own custom color palette for the traces.
faulkner_colorway = c("#132C53","#F27A18","#ae0700","#79b473","#38726c","#76bed0","#6b2d5c","#448b2d","#e6d812")

#This controls the background color for the entire chart. Probably best left white.
faulkner_paperbackground = c('rgba(255,255,255,0)')

#This controls the background for the plot. Probably best left white.
faulkner_plotcolor = c('rgba(255,255,255,.4)')

#Margin 

m <- list(l = 50, r = 50, b = 50, t = 50, pad = 4)

#Caption Style

fig_caption <- "font-family: 'Playfair Display','Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size:90%"

plot_font <- list(
  family = "'Playfair Display','Helvetica Neue',Helvetica,Arial,sans-serif",
  size = 15,
  color = '#363636')


```


```{r locations_raw}
dy_locations <- dy_events %>% 
                distinct(locationid, .keep_all = TRUE)
```


```{r map_locations_raw, out.width="768px",  out.height="605px"}

image_file <- "https://raw.githubusercontent.com/joostburgers/absalom_sentiment_analysis/master/images/dy_base_layer_4_2.png"

fig_race_map <-
  plot_ly(
    dy_locations,
    x = ~ true_x,
    y = ~ true_y,
    name=~display_label
   
  )
fig_race_map <- fig_race_map %>%
  layout(
    title = "Locations in Yoknapatawpha",
    xaxis = list(
      title = "",
      visible = FALSE,
      fixedrange = TRUE,
      range = c(0, 2008)
    ),
    yaxis = list(
      title = "",
      visible = FALSE,
      fixedrange = TRUE,
      range = c(-1660, 0)
    ),
    margin = m,
    font = plot_font,
    showlegend= FALSE,
    legend = list(
      title = list(text = "<b>Legend</b>"),
      itemsizing = 'constant'
    ),
    
    autosize = F,
      width = 768,
      height = 605,
    
    
    images = list(
      list(
        source =  image_file,
        xref = "x",
        yref = "y",
        x = 0,
        y = -40,
        sizex = 2008,
        sizey = 1660,
          sizing = "stretch",
        opacity = 0.8,
        layer = "below"
      )
      )
  )


fig_race_map

```


```{r heatmap_gender}
dy_gender <- dy_events %>% 
                group_by(gender) %>% 
                add_count(locationid) %>% 
                select(gender, n, display_label, startdate, true_x, true_y) %>%
                mutate(year = as.numeric(str_sub(startdate, 1, 4))) %>% 
                distinct()
                
```



```{r plot_heatmap_gender}

image_file <- "https://raw.githubusercontent.com/joostburgers/absalom_sentiment_analysis/master/images/dy_base_layer_4_2.png"

fig_race_map <-
  plot_ly(
    dy_gender,
    x = ~ true_x,
    y = ~ true_y,
    name= ~ gender,
    frame = ~year,
    color= ~gender,
     colors = faulkner_colorway[c(1,3:4)],
     type = 'scatter',
     mode = 'markers',
     size = ~n,
     sizes = c(3, max(dy_gender$n)*.15),
       hoverinfo='text',
     text= ~paste('Count:', n,'<br>',display_label),
       marker = list(
         sizemode='diameter',
                   opacity = .4,
                   line = list(width = 1, color = 'white')
        )
  )
fig_race_map <- fig_race_map %>%
  layout(
    title = "Locations in Yoknapatawpha",
    xaxis = list(
      title = "",
      visible = FALSE,
      fixedrange = TRUE,
      range = c(0, 2008)
    ),
    yaxis = list(
      title = "",
      visible = FALSE,
      fixedrange = TRUE,
      range = c(-1660, 0)
    ),
    margin = m,
    font = plot_font,
    showlegend= TRUE,
    legend = list(
      title = list(text = "<b>Legend</b>"),
      itemsizing = 'constant'
    ),
    
    autosize = F,
      width = 768,
      height = 605,
    
    
    images = list(
      list(
        source =  image_file,
        xref = "x",
        yref = "y",
        x = 0,
        y = -40,
        sizex = 2008,
        sizey = 1660,
          sizing = "stretch",
        opacity = 0.8,
        layer = "below"
      )
      )
  )


fig_race_map

```

